[build]
  publish = "wireframes"

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/preview"
  to = "/pages/preview.html"
  status = 200

[[redirects]]
  from = "/preview/*"
  to = "/pages/preview.html"
  status = 200

# Handle clean URLs without .html
[[redirects]]
  from = "/*"
  to = "/pages/:splat.html"
  status = 200 